// Run with: node scripts/generateSeed.js > scripts/seed_recipes.sql
// Then paste the output into the Supabase SQL Editor and run it.

const data = require('../scran_recipes.json');

const NUTRITION = {
  'asian-001':    { calories: 601, fat: 19, saturated_fat: 3,  fibre: 13, carbohydrates: 78, sugars: 4,  protein: 22, sodium: 820 },
  'asian-002':    { calories: 480, fat: 14, saturated_fat: 3,  fibre: 4,  carbohydrates: 52, sugars: 7,  protein: 32, sodium: 940 },
  'asian-003':    { calories: 520, fat: 22, saturated_fat: 8,  fibre: 3,  carbohydrates: 48, sugars: 6,  protein: 28, sodium: 760 },
  'asian-004':    { calories: 440, fat: 12, saturated_fat: 3,  fibre: 5,  carbohydrates: 58, sugars: 5,  protein: 24, sodium: 680 },
  'asian-005':    { calories: 390, fat: 10, saturated_fat: 2,  fibre: 4,  carbohydrates: 55, sugars: 8,  protein: 22, sodium: 560 },
  'italian-001':  { calories: 620, fat: 18, saturated_fat: 6,  fibre: 5,  carbohydrates: 82, sugars: 8,  protein: 28, sodium: 480 },
  'italian-002':  { calories: 540, fat: 20, saturated_fat: 8,  fibre: 4,  carbohydrates: 68, sugars: 6,  protein: 24, sodium: 560 },
  'italian-003':  { calories: 580, fat: 22, saturated_fat: 9,  fibre: 6,  carbohydrates: 72, sugars: 7,  protein: 26, sodium: 520 },
  'italian-004':  { calories: 650, fat: 24, saturated_fat: 10, fibre: 5,  carbohydrates: 78, sugars: 9,  protein: 30, sodium: 640 },
  'italian-005':  { calories: 490, fat: 16, saturated_fat: 6,  fibre: 4,  carbohydrates: 64, sugars: 7,  protein: 22, sodium: 440 },
  'mexican-001':  { calories: 560, fat: 22, saturated_fat: 8,  fibre: 7,  carbohydrates: 62, sugars: 6,  protein: 28, sodium: 700 },
  'mexican-002':  { calories: 480, fat: 18, saturated_fat: 6,  fibre: 9,  carbohydrates: 52, sugars: 8,  protein: 26, sodium: 760 },
  'mexican-003':  { calories: 520, fat: 20, saturated_fat: 7,  fibre: 8,  carbohydrates: 56, sugars: 5,  protein: 30, sodium: 680 },
  'mexican-004':  { calories: 440, fat: 16, saturated_fat: 5,  fibre: 10, carbohydrates: 48, sugars: 7,  protein: 24, sodium: 600 },
  'mexican-005':  { calories: 590, fat: 24, saturated_fat: 9,  fibre: 6,  carbohydrates: 60, sugars: 8,  protein: 32, sodium: 740 },
  'burgers-001':  { calories: 720, fat: 38, saturated_fat: 14, fibre: 4,  carbohydrates: 68, sugars: 12, protein: 36, sodium: 900 },
  'burgers-002':  { calories: 680, fat: 32, saturated_fat: 12, fibre: 5,  carbohydrates: 72, sugars: 10, protein: 34, sodium: 840 },
  'burgers-003':  { calories: 640, fat: 28, saturated_fat: 10, fibre: 5,  carbohydrates: 70, sugars: 14, protein: 30, sodium: 780 },
  'burgers-004':  { calories: 700, fat: 36, saturated_fat: 13, fibre: 4,  carbohydrates: 66, sugars: 11, protein: 38, sodium: 860 },
  'burgers-005':  { calories: 560, fat: 22, saturated_fat: 7,  fibre: 8,  carbohydrates: 64, sugars: 9,  protein: 28, sodium: 720 },
  'salads-001':   { calories: 280, fat: 14, saturated_fat: 3,  fibre: 8,  carbohydrates: 22, sugars: 10, protein: 18, sodium: 380 },
  'salads-002':   { calories: 320, fat: 16, saturated_fat: 4,  fibre: 9,  carbohydrates: 28, sugars: 12, protein: 20, sodium: 420 },
  'salads-003':   { calories: 260, fat: 12, saturated_fat: 2,  fibre: 10, carbohydrates: 20, sugars: 9,  protein: 16, sodium: 340 },
  'salads-004':   { calories: 340, fat: 18, saturated_fat: 5,  fibre: 7,  carbohydrates: 26, sugars: 11, protein: 22, sodium: 460 },
  'salads-005':   { calories: 300, fat: 14, saturated_fat: 3,  fibre: 11, carbohydrates: 24, sugars: 8,  protein: 20, sodium: 400 },
  'desserts-001': { calories: 420, fat: 18, saturated_fat: 10, fibre: 2,  carbohydrates: 62, sugars: 42, protein: 6,  sodium: 180 },
  'desserts-002': { calories: 380, fat: 16, saturated_fat: 9,  fibre: 3,  carbohydrates: 58, sugars: 38, protein: 7,  sodium: 160 },
  'desserts-003': { calories: 450, fat: 20, saturated_fat: 12, fibre: 2,  carbohydrates: 64, sugars: 46, protein: 7,  sodium: 200 },
  'desserts-004': { calories: 400, fat: 17, saturated_fat: 10, fibre: 4,  carbohydrates: 56, sugars: 40, protein: 6,  sodium: 170 },
  'desserts-005': { calories: 460, fat: 22, saturated_fat: 13, fibre: 2,  carbohydrates: 60, sugars: 44, protein: 8,  sodium: 210 },
};

function esc(str) {
  return str.replace(/'/g, "''");
}

function toSqlArray(arr) {
  return JSON.stringify(arr);
}

const rows = data.recipes.map((r) => {
  const n = NUTRITION[r.id] || null;
  return `  ('${r.id}', '${esc(r.title)}', '${esc(r.description)}', '${esc(r.category)}', ${r.cookTime}, ${r.prepTime}, ${r.servings}, '${r.difficulty}', '${esc(JSON.stringify(r.ingredients))}', '${esc(JSON.stringify(r.steps))}', NULL, '${esc(JSON.stringify(n))}')`;
});

console.log('-- Seed: 30 recipes for SCRAN');
console.log('-- Generated by scripts/generateSeed.js — do not edit by hand.');
console.log('');
console.log('insert into recipes (id, title, description, category, cook_time, prep_time, servings, difficulty, ingredients, steps, image_url, nutrition)');
console.log('values');
console.log(rows.join(',\n'));
console.log('on conflict (id) do nothing;');
